//
//  HotwordSettingsView.swift
//  Voxa
//
//  Phase 4: 热词管理页 — 列表、CRUD、优先级、reloadHotwords
//

import SwiftUI
import SwiftData

/// 热词设置：查看、新增、编辑、删除热词；增删改后需触发 SessionCoordinator.reloadHotwords（由调用方注入或通过通知）
struct HotwordSettingsView: View {
    @Environment(\.modelContext) private var modelContext
    @Query(sort: [
        SortDescriptor<Hotword>(\.priority, order: .reverse),
        SortDescriptor<Hotword>(\.createdAt)
    ]) private var hotwords: [Hotword]
    @State private var showingAdd = false
    @State private var editingHotword: Hotword?

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Spacer()
                Button("添加热词") { showingAdd = true }
                    .buttonStyle(.borderedProminent)
                    .padding(.horizontal)
                    .padding(.vertical, 8)
            }
            .background(.regularMaterial)
            List {
                ForEach(hotwords) { h in
                    HStack {
                        VStack(alignment: .leading, spacing: 2) {
                            Text(h.pattern)
                                .font(.headline)
                            Text("→ \(h.replacement)")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                            HStack(spacing: 4) {
                                Text("优先级 \(h.priority)")
                                    .font(.caption2)
                                if h.isAutoGenerated {
                                    Text("自动添加")
                                        .font(.caption2)
                                        .foregroundStyle(.secondary)
                                }
                            }
                        }
                        Spacer()
                        Button("编辑") { editingHotword = h }
                        Button("删除", role: .destructive) { deleteHotword(h) }
                    }
                }
            }
            .overlay {
                if hotwords.isEmpty {
                    ContentUnavailableView("暂无热词", systemImage: "textformat", description: Text("点击上方「添加热词」创建替换规则"))
                }
            }
        }
        .sheet(isPresented: $showingAdd) {
            HotwordEditSheet(modelContext: modelContext, hotword: nil, onReload: notifyReloadHotwords) {
                showingAdd = false
            }
        }
        .sheet(item: $editingHotword) { h in
            HotwordEditSheet(modelContext: modelContext, hotword: h, onReload: notifyReloadHotwords) {
                editingHotword = nil
            }
        }
    }

    private func deleteHotword(_ h: Hotword) {
        modelContext.delete(h)
        try? modelContext.save()
        notifyReloadHotwords()
    }
}

// MARK: - 热词编辑表单
struct HotwordEditSheet: View {
    let modelContext: ModelContext
    let hotword: Hotword?
    var onReload: (() -> Void)?
    let onDismiss: () -> Void

    @State private var pattern = ""
    @State private var replacement = ""
    @State private var priority = 0

    var body: some View {
        Form {
            TextField("匹配模式", text: $pattern)
            TextField("替换为", text: $replacement)
            Stepper("优先级: \(priority)", value: $priority, in: -100...100)
        }
        .formStyle(.grouped)
        .padding()
        .onAppear {
            if let h = hotword {
                pattern = h.pattern
                replacement = h.replacement
                priority = h.priority
            }
        }
        .toolbar {
            ToolbarItem(placement: .cancellationAction) {
                Button("取消") { onDismiss() }
            }
            ToolbarItem(placement: .confirmationAction) {
                Button("保存") {
                    save()
                    onReload?()
                    onDismiss()
                }
                .disabled(pattern.isEmpty || replacement.isEmpty)
            }
        }
    }

    private func save() {
        if let h = hotword {
            h.pattern = pattern
            h.replacement = replacement
            h.priority = priority
        } else {
            let h = Hotword(pattern: pattern, replacement: replacement, priority: priority)
            modelContext.insert(h)
        }
        try? modelContext.save()
    }
}

/// 热词增删改后发送此通知，SessionCoordinator 或上层可监听并调用 reloadHotwords
extension Notification.Name {
    static let voxaReloadHotwords = Notification.Name("VoxaReloadHotwords")
}

private func notifyReloadHotwords() {
    NotificationCenter.default.post(name: .voxaReloadHotwords, object: nil)
}

// Preview 需在带 .modelContainer 的父视图中使用（如 SettingsView）
