//
//  Hotword.swift
//  Voxa
//
//  Phase 3: SwiftData 热词模型 - 用于 STT 原始文本的校正替换
//

import Foundation
import SwiftData

/// 热词：匹配模式、替换文本、优先级、是否自动生成
@Model
final class Hotword {
    @Attribute(.unique) var id: String
    var pattern: String
    var replacement: String
    var priority: Int
    var isAutoGenerated: Bool
    var createdAt: Date

    init(
        id: String = UUID().uuidString,
        pattern: String,
        replacement: String,
        priority: Int = 0,
        isAutoGenerated: Bool = false,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.pattern = pattern
        self.replacement = replacement
        self.priority = priority
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = createdAt
    }
}
